### PR TITLE
Grid view is done?

### PR DESCRIPTION
**Pull request by teddyh-io**
Hey @anott03 and @liam-strand!
@ella-guo-yixin and I just finished the grid view, or at least we think.
It should take in an array of components and display them in a grid.
Please let me know if we need to make changes!

### CODE REVIEW

**Review by liam-strand — CHANGES_REQUESTED** [review]
Hey there, I just tried this out and it looks like everything is tiled into just one row. Can you please update the styling so that the components are tiled in a grid with as many rows as is necessary?

**Comment by ella-guo-yixin** [comment]
Hey Liam, we updated our grid view component, and we think that should be fine now!

**Comment by anott03** [comment]
Looks great! Thank you guys!

**Review by anott03 — APPROVED** [review]

**Review by liam-strand — COMMENTED** [review]
Great work!

**Pull request merged**
